import { TagType } from "@/generated/prisma/client.js";

export const tagLabels: Record<TagType, string> = {
  [TagType.ALCOHOLIC_DRINK]: "Bebidas alcoólicas",
  [TagType.APPETIZER]: "Aperitivos",
  [TagType.BREAKFAST]: "Café da manhã",
  [TagType.BURGER]: "Hambúrgueres",
  [TagType.CAKE]: "Bolos",
  [TagType.COFFEE]: "Café",
  [TagType.COLD_DRINK]: "Bebidas frias",
  [TagType.COMBO]: "Combos",
  [TagType.COOKIE]: "Biscoitos",
  [TagType.DESSERT]: "Sobremesas",
  [TagType.DINNER]: "Jantar",
  [TagType.DRINK]: "Bebidas",
  [TagType.FISH]: "Peixes",
  [TagType.FOOD]: "Alimentos",
  [TagType.FRUIT]: "Frutas",
  [TagType.GLUTEN_FREE]: "Sem Glúten",
  [TagType.GRILL]: "Churrasco",
  [TagType.HOT_DRINK]: "Bebidas quentes",
  [TagType.ICE_CREAM]: "Sorvetes",
  [TagType.JUICE]: "Sucos",
  [TagType.LUNCH]: "Almoço",
  [TagType.MEAT]: "Carnes",
  [TagType.MILK_SHAKE]: "Milk Shakes",
  [TagType.NON_ALCOHOLIC_DRINK]: "Bebidas não alcoólicas",
  [TagType.PASTA]: "Massas",
  [TagType.PASTRY]: "Padarias",
  [TagType.PIE]: "Tortas",
  [TagType.PIZZA]: "Pizzas",
  [TagType.SALAD]: "Saladas",
  [TagType.SANDWICH]: "Sanduíches",
  [TagType.SIDE]: "Entradas",
  [TagType.SMOOTHIE]: "Smoothies",
  [TagType.SNACK]: "Snacks",
  [TagType.SODA]: "Refrigerantes",
  [TagType.SOUP]: "Sopas",
  [TagType.SUSHI]: "Sushi",
  [TagType.TEA]: "Chá",
  [TagType.VEGAN]: "Vegano",
  [TagType.VEGETABLE]: "Vegetais",
  [TagType.VEGETARIAN]: "Vegetariano",
};
