-- CreateEnum
CREATE TYPE "ViewType" AS ENUM ('VIEW_CATALOG', 'VIEW_OWN_BAG', 'VIEW_OWN_FAVORITES', 'MAKE_OWN_ORDER', 'VIEW_OWN_ORDERS', 'VIEW_OWN_ADDRESSES', 'CREATE_OWN_ADDRESS', 'VIEW_ESTABLISHMENTS', 'CREATE_ESTABLISHMENT', 'VIEW_CUSTOMERS', 'CREATE_ESTABLISHMENT_OWNER', 'VIEW_PRODUCTS', 'CREATE_PRODUCT', 'VIEW_PRODUCT_CATEGORIES', 'CREATE_PRODUCT_CATEGORY', 'VIEW_ORDERS', 'VIEW_COUPONS', 'CREATE_COUPON');

-- AlterTable
ALTER TABLE "menus" ADD COLUMN     "view_type" "ViewType";

-- AlterTable
ALTER TABLE "submenus" ADD COLUMN     "view_type" "ViewType";
